### ISSUE TITLE
Getting parts or characteristics with specified attributes does not work

### ISSUE THREAD

**Issue by czfechner** [ZEISS-PiWeb/PiWeb-Api#10]
**Affected Version(s)**
1.0 - 4.0

**Describe the bug**
When I search for specific part or characteristic attributes wihout a part specified I get the part without the requested attributes.

**To Reproduce**
See [JIRA issue PIWEB-10842](https://bugtracker.zeiss-izm.de/browse/PIWEB-10842)

**Expected behavior**
See [JIRA issue PIWEB-10842](https://bugtracker.zeiss-izm.de/browse/PIWEB-10842)

**Comment by czfechner** [comment]
Created Pull-Request https://github.com/ZEISS-PiWeb/PiWeb-Api/pull/11.

**Comment by czthiele** [comment]
Fixed with Pull-Request #11
