### ISSUE TITLE
Unable to load empty values

### ISSUE THREAD

**Issue by jdunkelmann** [ZEISS-PiWeb/PiWeb-Api#125]
Version 7.6.5.0

When loading all values from a given measurement, only characteristics with an actual value assigned to attribute "1" are provided by the REST API. PiWeb Planner does show all characteristics with empty values though. I need to access these characteristics in order to write the reason for being unmeasured into another value attribute. Can this be achieved somehow?

**Comment by czthiele** [comment]
Hello @jdunkelmann,

correct, the API will only return the characteristic if there is any value for a value attribute present (be it K1 or any other value attribute).
In this case you need to fetch the characteristics of the part on your own and match them with your measured characteristics, to get all unmeasured characteristics. Then you can simply add the unmeasured characteristics and their value attributes to the measurement and update it as usual.

**Comment by jdunkelmann** [comment]
Hi, I was expecting you to say this. So I did exactly what you are proposing: I added a value for unmeasured chars with keeping K1 empty but assigning a value to K115 (value attribute). I can see this entry now when opening the measurement from PiWeb Planner. Still, the REST API won't give me that characteristic.

**Comment by czthiele** [comment]
I actually cannot reproduce this problem using the exact version Server 7.6.5.
My test looks like this inside PiWeb Planner:
<img src="https://user-images.githubusercontent.com/51409393/145575891-f9e6eb14-ef60-467a-9081-052093b2660a.png" width="500">

Requesting the values using
`/DataServiceRest/values?partPath=/Part`

will correctly return two characteristics:
```json
[
    {
        "characteristics": {
            "8cba32a7-39ba-489a-8948-cd3ab2317f52": {
                "1": 0.83556854724884033
            },
            "fabd3564-69f7-495d-b20e-d9500475331a": {
                "2": "MyValue"
            }
        },
        "uuid": "1801b6f1-f22e-4b64-b2d4-90dc93ae1421",
        "partUuid": "b1232dfb-399e-41ba-9909-8322021e7c23",
        "lastModified": "2021-12-10T12:39:19.743Z",
        "created": "2021-12-10T12:04:48.48Z",
        "attributes": {
            "4": "2021-06-09T22:00:00Z"
        }
    }
]
```

Are you perhaps using any attribute restriction, e.g. the parameter `requestedValueAttributes` in the query?

**Comment by jdunkelmann** [comment]
Alexander, this screenshot was very helpful! The entries I was focusing on did not have any attributes filled out. So this makes perfect sense now. Thanks for shedding some light on this!
