### ISSUE TITLE
Timeout Probleme beim Aufruf der PiWeb API 

### ISSUE THREAD

**Issue by y1tdamba** [ZEISS-PiWeb/PiWeb-Api#129]
Sehr geehrte Damen und Herren,

folgende Version wird verwendet:
- PiWeb Enterprise Version 7.8.6 Windows Server 2016 Standard R2 
- Datenbank SQL Server 2017 

LastSpitzen mit Timeouts auf Applikations-Server und Datenbank-Server gibt es nicht, die beiden Server sind nicht ausgelastet.

Aktuell haben wir das Problem, dass es immer wieder beim Aufruf der PiWeb API zu Timeout Problemen kommt.

Das ITSM hat meine Fehlermeldung irgendwie gekürzt. Hier nochmal:
Feb 01 09:05:33 32960.5743 BizTalk_Server The adapter failed to transmit message going to send port "SP_PiWeb_GetCharacteristics.WebHttp.TwoWay" with URL https://PiWebServer/dataServiceRest.
It will be retransmitted after the retry interval specified for this Send Port.
Details:"System.TimeoutException: The HTTP request to 'https://PiWebServer/dataServiceRest/characteristics?partPath=/.../'
has exceeded the allotted timeout of 00:01:00. The time allotted to this operation may have been a portion of a longer timeout. ---

Wir erhalten immer noch Timeouts:
Feb 01 11:05:32 32960.5743 BizTalk_Server The adapter failed to transmit message going to send port "SP_PiWeb_GetCharacteristics.WebHttp.TwoWay" with URL https://PiWebServer/dataServiceRest. It will be retransmitted after the retry interval specified for this Send Port. Details:"System.TimeoutException: The HTTP request to 'https://PiWebServer/dataServiceRest/characteristics?partPath=/' has exceeded the allotted timeout of 00:01:00. The time allotted to this operation may have been a portion of a longer timeout. ---> System.Net.WebException: The request was aborted: The request was canceled. at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelAsyncRequest.CompleteGetResponse(IAsyncResult result) --- End of inner exception stack trace --- Server stack trace: at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result) at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result) at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result) at System.ServiceModel.Channels.ServiceChannel.EndRequest(IAsyncResult result) Exception rethrown at [0]: at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg) at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type) at System.ServiceModel.Channels.IRequestChannel.EndRequest(IAsyncResult result) at Microsoft.BizTalk.Adapter.Wcf.Runtime.WcfClient`2.RequestCallback(IAsyncResult result)".

In den LogFiles findet man dazu auch viele Einträge Request finished in 14.2457ms 401  dazu. 

(null)                    [(null)  ] [ll)] [(null)                        ] [2544 9ffcf2c0] 2022-02-01 13:05:31,493  INFO  AspNetCore                - Request finished in 7.6056ms 200 application/json; charset=utf-8
(null)                    [(null)  ] [ll)] [(null)                        ] [2544 1914ebbb] 2022-02-01 13:05:31,530  INFO  AspNetCore                - Request starting HTTP/1.1 GET https://PiWebServer/dataServiceRest/characteristics?partPath=%2f... application/xml; charset=utf-8 
(null)                    [(null)  ] [ll)] [(null)                        ] [2544 1914ebbb] 2022-02-01 13:05:31,550  INFO  AspNetCore                - Request finished in 19.2743ms 401 

Könnten Sie bitte prüfen warum es zu diesen Timeout Problemen beim Aufruf der PiWeb API kommt.

Diese Aufrufe finden alle paar Minuten statt

Bitte um Rückinfo

Mit freundlichen Grüßen / Kind Regards

Thomas Dambacher
Business Applications SMT (SMT-IA)
ZEISS Sparte Semiconductor Manufacturing Technology
 
Carl Zeiss SMT GmbH
ZEISS Gruppe
Rudolf-Eber-Straße 2
73447 Oberkochen

**Comment by czthiele** [comment]
Guten Tag @y1tdamba,

kurz Vorweg: ich habe Ihre Anfrage kurzerhand noch etwas "anonymisiert", da hier auf GitHub sonst jeder Ihre Server-Information sehen kann (auch wenn dieser intern läuft und nicht erreichbar sein sollte).

Um die erste Frage zu beantworten: die Einträge mit dem Statuscode 401 sind keine Ursache, diese stehen für die Anfrage eines Nutzers der nicht authentifiziert werden konnte und darum abgewiesen wird. Das würde sich aber nicht in einem Timeout äußern.

Grundlegend fällt mir erstmal auf das der Timeout bei Ihnen eine Minute beträgt (has exceeded the allotted timeout of 00:01:00). Nutzt Ihre Software unser C#NuGet, oder wird die API direkt per Web-Request angesprochen?

Unser eigener Standard-Timeout in den PiWeb-Clients und dem C# NuGet ist 5 Minuten (dieser kann jedoch auch überschrieben worden sein). Je nach Datenmenge, Übertragungsrate oder bspw. aktuell VPN kann es vorkommen das Ihr Timeout zu gering gewählt ist. 
Wenn Sie das C# NuGet nutzen sollte geprüft werden, ob der Standard-Timeout überschrieben wird.
Wenn die API direkt angesprochen wird dann muss in der entsprechend genutzten Programmbibliothek der Timeout erhöht werden.

Ich denke dieser Punkt sollte erstmal geprüft werden, es ist durchaus möglich das ein höherer Timeout (ähnlich unserem eigenen Standardwert) schon ausreicht.

Mit freundlichen Grüßen
czthiele
