### ISSUE TITLE
Wrong Description from Data Service Document v1.4 

### ISSUE THREAD

**Issue by WilliamLei0827** [ZEISS-PiWeb/PiWeb-Api#14]
**Affected Version(s)**
http://zeiss-piweb.github.io/PiWeb-Api/dataservice/v1.4/

**Describe the bug**
The PartPost method example's request jsonbody is not correct.

**Expected behavior**
"path": "/metal part"   should be changed to correct format like "path": "PP:/part A/part B/"

**Screenshots**
![image](https://user-images.githubusercontent.com/49181085/64228217-b1c2a900-cf18-11e9-9fd5-31c40abcaad5.png)

**Comment by daniel-lahmann** [comment]
Thank you @WilliamLei0827! Mistakes have been fixed.
