### ISSUE TITLE
Differentiate search query between upper and lower case (a ≠ A)

### ISSUE THREAD

**Issue by 1Stefan** [ZEISS-PiWeb/PiWeb-Api#186]
Hi!
We use:
REST API (PiWeb Enterprise 8.2.3.0)

Is it possible to differentiate a search query between upper and lower case (a ≠ A)?

Example:

https://piwebserver/0000/DataServiceRest/values?searchCondition=110=[Abc]
 
https://piwebserver/0000/DataServiceRest/values?searchCondition=110=[abc]

currently gives the same output but should produce different results!?

**Comment by czthiele** [comment]
Hello @1Stefan, good news!

coming with the next PiWeb release including DataService version 1.9, measurement and value enpoints will have the possibility to specify case sensitivity in combination with the search condition. Please refer to the documentation after release for more information.

Regards,
czthiele
