### ISSUE TITLE
rawDataInformation endpoint not working

### ISSUE THREAD

**Issue by jdunkelmann** [ZEISS-PiWeb/PiWeb-Api#191]
Hi,
I am starting to work with raw data REST service, version 7.6.2. I am struggeling with the documented endpoints.

http://server:port/rawDataServiceRest/rawDataInformation/measurement/75ae8256-5c63-44a5-aaca-ccaae579b232 gives me 404 -  "Endpoint 'rawDataInformation' does not exist."

http://server:port/rawDataServiceRest/rawData/measurement/75ae8256-5c63-44a5-aaca-ccaae579b232 gives me what I expected with the above URL but without file content.

Can you explain what I am doing wrong?

**Comment by czthiele** [comment]
Hello @jdunkelmann,

sorry for the late reply. It is important to note that the documentation will show the most current version when navigating using the links on http://zeiss-piweb.github.io/PiWeb-Api. Currently this is 1.7 for the RawDataServiceRest, but your PiWeb Server 7.6 only supports version 1.4 (see Interface information in the doc). So you need to select the correct version in the dropdown to see the right documentation for your version: 
![image](https://user-images.githubusercontent.com/51409393/207084436-3eff4930-0f91-4516-939a-a63c9e6b45cc.png)

In this special case we added a new endpoint for rawdata information (/rawdataInformation), but only in newer versions. The old endpoint still exists, but in your case you wanted to use the newer endpoint which your server does not know yet.
Things should clear up when you read the doc for RawDataServiceRest version 1.4.

http://server:port/rawDataServiceRest/rawData/measurement/75ae8256-5c63-44a5-aaca-ccaae579b232 gives you the information for all raw data of this entity. Then you append the key of the file you want to access to get content:
http://server:port/rawDataServiceRest/rawData/measurement/75ae8256-5c63-44a5-aaca-ccaae579b232/KEY

I hope this helps.
Regards, czthiele

**Comment by jdunkelmann** [comment]
Thanks Alexander. This explains it all. Currently we are facing a mix of PiWeb versions that I wasn't aware of.
