### ISSUE TITLE
Build failed Api.Tests - CS0246

### ISSUE THREAD

**Issue by ThomasFischer1** [ZEISS-PiWeb/PiWeb-Api#21]
**Affected Version(s)**
Commit 172ec88b, developer

**Describe the bug**
CS0246 - " Error CS0246: Der Typ- oder Namespacename "AutoFixture" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis). (17, 8)"
more assemblies: AutoFixture, Newtonsoft, NUnit, TestFixtureAttribute, TestFixture, Fixture, TestAttribute, Test

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
VS2019

**Comment by czthiele** [comment]
The first thing you should try is doing a NuGet restore, in case VS2019 did not do this prior to building. Right click on the API solution in VisualStudio, and select NuGet Package restore. 

Please let me know if this already solved your issue.

**Comment by ThomasFischer1** [comment]
After restore ... 

> Error		Error occurred while restoring NuGet packages: The feed 'IMT [http://nuget-imt.zeiss.org:81/nuget/Default/]' lists package 
'NuGet.Frameworks.5.0.0' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again.

>

**Comment by czthiele** [comment]
It seems that you are using the company's nuget feed.
Try switching the nuget feed to the official source. Right click on the solution and choose 'Manage NuGet packages', and in the upper right corner select 'nuget.org' as the package source from the dropdown, at the moment it should display the feed 'IMT'. 

If nuget.org is not in the list, then use the options menu next to it and add the source nuget.org with the link https://api.nuget.org/v3/index.json

After that, try the package restore again. It should download all neccessary packages now.
Please note when switching back to other projects: don't forget to change the feed back to 'IMT' if these projects require nugets from there.
