### ISSUE TITLE
API Connectivity to the PiWeb Cloud

### ISSUE THREAD

**Issue by pavankumar88veeru** [ZEISS-PiWeb/PiWeb-Api#225]
**I am using:**
[*] C# NuGet

How can we connect to the PiWeb Cloud, and do the same functionality as the PiWeb On-Premises solution with the PiWeb-Api.

**Comment by czthiele** [comment]
Hi @pavankumar88veeru,

the [PiWeb API-Training](https://github.com/ZEISS-PiWeb/PiWeb-Training) repository contains a working example on using OIDC to connect to a PiWeb cloud database using the C# Nuget, see [here](https://github.com/ZEISS-PiWeb/PiWeb-Training#piwebapi---oidc-authentication).

Simply open the project PiWeb.Api.Training.OidcAuth and take a look at it. This minimal examples opens a WebView2 browser window to do the login process and hands over the auth token to the C# client.

Best regards
czthiele

**Comment by R3d-Dragon** [comment]
Hi,

the only difference between PiWeb onPremise and cloud is the authentication. PiWeb cloud is using OIDC as authentication method.
Please have a look into our OIDC Authentication example project: https://github.com/ZEISS-PiWeb/PiWeb-Training#piwebapi---oidc-authentication .
