### ISSUE TITLE
Getting the additional data from measurements

### ISSUE THREAD

**Issue by StephanKrauth** [ZEISS-PiWeb/PiWeb-Api#226]
**I am using:**
[X ] C# NuGet
[ ] REST API

**Question**
Each of my measurements have an XML file as additional data. I would like to read this file via C# Code.

1. i wrote the code to get all measurements of one part

![01_Code_Measurements](https://github.com/ZEISS-PiWeb/PiWeb-Api/assets/147132690/c72ad021-53f3-4137-9fd1-91eac13f6ecb)

![02_Measurements_Content](https://github.com/ZEISS-PiWeb/PiWeb-Api/assets/147132690/5f5c06ae-8684-4d8a-b12e-2d70bbe11a5b)

2. i tried to get the additional data via the function "GetRawDataForMeasurents" and used the measurement uuid which i got from step 1.
![04_Code_Additinal_Data](https://github.com/ZEISS-PiWeb/PiWeb-Api/assets/147132690/61d40620-378c-4c32-91d5-3c9a0d3b9f43)

4. i get no data. I think its because of the rawDataKey.
![05_Problem_Additinal_Data](https://github.com/ZEISS-PiWeb/PiWeb-Api/assets/147132690/13db4607-a3f6-45e8-b2e8-ab9c4eeef834)
![03_Key](https://github.com/ZEISS-PiWeb/PiWeb-Api/assets/147132690/92e11bdf-0911-4488-bec1-fecde5b6ad99)

First question: what ist the rawDataKey which is needed for the function?
Second question: if i would have the correct rawDataKey, is this the correct way to get the xml file from the additional data?

**Comment by nicoweh** [comment]
1. The `rawDataKey` is a number to identify the rawData within an entity (like a part, characteristic, measurement). This is required, because you can have more than one rawData attached to an entity.
If you don't know the key (from the time when you created the rawData), you will get it and other rawDataInformation when you call `ListRawDataForMeasurements` from your `RawDataServiceRestClient` instance.
2. Yes, it is correct to use `GetRawDataForMeasurement` then.

**Comment by StephanKrauth** [comment]
Thanks for your answer.
But i still have the problem, that i get no data.
The function ListRawDataForMeasurements needs a array of Guid. So i made a new Guid element with the first uuid from my measurements and put this in an array.
![06_ListRawDataForMeasurements](https://github.com/ZEISS-PiWeb/PiWeb-Api/assets/147132690/3d54ab64-06bc-46a4-b6a9-7abae864aa57)
But i get again no data
![07_ListRawDataForMeasurements2](https://github.com/ZEISS-PiWeb/PiWeb-Api/assets/147132690/f53a4480-e4d9-438d-b853-e992707b7bb7)

**Comment by nicoweh** [comment]
`ListRawDataForMeasurements` and other methods are `async` methods and you will get a `Task` object. The `Result` property is `null` until the `Task` is completed.

**Comment by StephanKrauth** [comment]
Do you have a code example, how the async method works? I think there isnt something in the example project.

**Comment by nicoweh** [comment]
Async method is not a PiWeb API feature, it's a .Net language feature. Please have a look at the C# documentation.
In our PiWeb Training example project you will also find the `await` keyword in the `async Task` methods.

**Comment by czthiele** [comment]
Hello @StephanKrauth,

more examples for the usage of our C# NuGet can be found in the documentation [here](http://zeiss-piweb.github.io/PiWeb-Api/sdk/v8.1/). You can also find information about fetching additional data (raw data) in the section [further down](http://zeiss-piweb.github.io/PiWeb-Api/sdk/v8.1/#ba-rawData). You will see that all methods from the NuGet are async and used together with `await` [(asynchronous programming)](https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/async-scenarios). 
In your previous code you used `.Result` to get the measurements. This makes the code synchronous, meaning your application will wait and "hang" until the result of the task is returned. The best approach is to make yourself familiar with the `async/await` pattern in C# and use it in your app, then you should get the desired results, and your app will stay responsive.

**Comment by StephanKrauth** [comment]
I'm happy that you can help me here, thank you very much for that. The note with .Result helped. Yes, I know, this is the syncron method, but I currently have no problem with runtimes and would like to get to the data first for testing and intepreting.

I hope that this is my last question:
Now i get values with the function GetRawDataForMeasurements. The File in additional data is a xml file, but i only get a list of numbers. Do i have to convert them or something like that?
![08_Outliers](https://github.com/ZEISS-PiWeb/PiWeb-Api/assets/147132690/7228f81d-bec4-4ab2-bf94-853a810e7e87)

**Comment by StephanKrauth** [comment]
Thanks a lot for your help. The note with .Result helped me to get the Data. I know, iam working snycron and not asyncron with this method, but actually i have no problems with duration or hanging. First i want to get the data and work with them. If I need a faster running time later, I have to change it.
