### ISSUE TITLE
Retrieve limits configuration

### ISSUE THREAD

**Issue by jdunkelmann** [ZEISS-PiWeb/PiWeb-Api#236]
Hi, using REST API 1.9 (PiWeb 8.4.15), is there a way to retrieve the configuration of limits (warning, specs, etc.) so we can expose actual values using the correct colors (green - yellow - red)?

**Comment by czthiele** [comment]
Hi @jdunkelmann,

just to make sure, you mean the tree view context menu entry 'Configure limits' / 'Grenzen konfigurieren' and the configuration which you can do in the upcoming dialogue?

Best regards
czthiele

**Comment by jdunkelmann** [comment]
Yes, Alexander.


Mit freundlichen Grüßen / Best regards

Jan Dunkelmann
Geschäftsführer / Managing Director

***@***.***
QC-S GmbH
Seelandstr. 14-16 |  23569 Luebeck |  Germany
phone     +49 (451) 160 858-41
mobile    +49 (172) 921 8695
email      ***@***.***
www.qc-s.com<http://www.qc-s.com/>
_______________________________________
Handelsregister / Registration: Amtsgericht Lübeck HRG 13748
Geschäftsführer / General Manager: Jan Dunkelmann
Steuer-Nr.: 22/296/19521
USt-IDNr. / VAT reg. no.: DE 294319941

Von: Alexander Thiele ***@***.***>
Gesendet: Dienstag, 13. Februar 2024 08:59
An: ZEISS-PiWeb/PiWeb-Api ***@***.***>
Cc: Jan Dunkelmann | QC-S ***@***.***>; Mention ***@***.***>
Betreff: Re: [ZEISS-PiWeb/PiWeb-Api] Retrieve limits configuration (Issue #236)


Hi @jdunkelmann<https://github.com/jdunkelmann>,

just to make sure, you mean the tree view context menu entry 'Configure limits' / 'Grenzen konfigurieren' and the configuration which you can do in the upcoming dialogue?

Best regards
czthiele

**Comment by czthiele** [comment]
Hi @jdunkelmann,

then it is a little bit more tricky. This configuration is also "saved" in the database, but in the sense of beeing attached as a file to the root part. There should be a _ToleranceLimits.settings_ file as additional data of the root part (only if the settings are different then the default values!). This file contains the settings of the limits dialogue in JSON format. You could take a look if this contains the information which you need, together with the other values at attribute level.

But please mind that this is not officially documented, so we cannot guarantee the same compatibility as we do for the public APIs. The file structure may change one day.

Best regards
czthiele
