### ISSUE TITLE
Send data from PiWeb Async 

### ISSUE THREAD

**Issue by Thorbenl** [ZEISS-PiWeb/PiWeb-Api#242]
**I am using:**
[x] C# NuGet
[x] REST API

**Used version**
PiWeb Server 8.6

**Question**
I would like send data from `/DataServiceRest/Measurements` or `/DataServiceRest/Characteristics` to my Service Bus, or RabbitMQ Queue. 
Meaning: whenever a new measurement was done, I would like to trigger an event inside the PiWeb code, and send that data towards somewhere else.

Does PiWeb have something like this inbuilt? We dont want to do polling. Webhooks would also be ok, but I am generally curious what is possible here.

**Comment by czthiele** [comment]
Hello @Thorbenl,

unfortunately for version 8.6 of PiWeb server the only available option would be polling.

But we are currently working on this and planning to release the first iteration of an "events" feature with the next release this year. This will allow you to subscribe to PiWeb server events using a technology like SignalR, and your application will receive new events directly from the server _without_ polling, e.g. when a measurement or characteristic is created, edited or deleted. You could then simply react to this event and send it to any other service. So the only thing you need is a small application which receives events from PiWeb and routes them to your desired destination.
I hope that this would work you, I would keep this question here open and notify you when this new feature is released and documentation available.

Regards,
czthiele

**Comment by Thorbenl** [comment]
Thanks for the quick answer @czthiele  :) What timeframe are we looking at it for the beta of this? :)

**Comment by czthiele** [comment]
@Thorbenl Currently the next release is scheduled for october this year (if there are no unexpected problems), and we would also try to provide public API documentation at the same time.
