### ISSUE TITLE
[Question] How I can use the API with ActiveDirectory Authentication

### ISSUE THREAD

**Issue by WilliamLei0827** [ZEISS-PiWeb/PiWeb-Api#29]
Dear Developer,

I use the API through http. I already can do something like CreatePart/CreateMeasurement with the url and Json.  
Now i have a piweb server which the access control type is Active Driectory Integration(Windows authentication). I want to know how i can do the same thing like CreatePart with the windows authentication server?

Thanks~

**Comment by czjlorenz** [comment]
Using the .NET SDK you can set the authentication container with the authentication mode on the RestClient object.

```
var client = new DataServiceRestClient(new System.Uri("http://127.0.0.1:8080/"));
client.AuthenticationContainer = new AuthenticationContainer(AuthenticationMode.Windows);
```

**Comment by WilliamLei0827** [comment]
Thank you very much for your answer.It's been successful with the .Net SDK.
What I want to know is how to use Windows authentication when I am using it this way through the REST API?
For example, how do I authenticate Windows permissions when I run the following code?

                 `public bool Post(string url, string jsonData)
        {
            using (var httpClient = new HttpClient())
            {
                try
                {
                    var response = httpClient.PostAsync(url, new StringContent(jsonData)).Result;                                
                    var statusCode = response.StatusCode;
                    //201 (Created)
                    if (statusCode == System.Net.HttpStatusCode.Created)
                    {
                        return true;
                    }
                    else
                    {
                        Error errorMsg = JsonConvert.DeserializeObject<Error>(response.Content.ReadAsStringAsync().Result);
                        throw new Exception(statusCode.ToString() + " bad " + errorMsg.Message);
                    }
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
        }`

**Comment by czjlorenz** [comment]
The "magic" happens in `RestClientBase.UpdateUseWindowsCredentials()`, see [RestClientBase.cs:508](https://github.com/ZEISS-PiWeb/PiWeb-Api/blob/78ac6ab699229722733dcf930772421fd4d8ac11/src/Api.Rest/Common/Client/RestClientBase.cs#L508)

`_WebRequestHandler.UseDefaultCredentials = useDefaultCredentials;`

For your example you new to create the HttpClient class like this:
`var webRequestHandler = new WebRequestHandler();`
`webRequestHandler.UseDefaultCredentials = true;`
`var httpClient = new HttpClient( webRequestHandler );`

**Comment by WilliamLei0827** [comment]
I succeeded in the test. It's really magic and your answer is really helpful to me. Thank you so much :)
