### ISSUE TITLE
Error when POSTing to Raw Data Service using Python

### ISSUE THREAD

**Issue by czpercle** [ZEISS-PiWeb/PiWeb-Api#37]
**Affected Version(s)**
Server 7.4.5

**Describe the bug**
When attempting to perform a POST on the rawData/<entity>/<uuid> endpoint (to attach a file to a measurement), the server returns an error that a string is not a property base64 string.

**To Reproduce**
1. Upload "Test.qdb" to a running PiWeb server. The database should now contain a part at /Test Gruppe/Test with several characteristics, one of which is 01 with a sub-characteristic X.
2. Run the Python script "test_createrawdata.py". The script queries the part to get the characteristic UUID of "01/X" and to get a specific existing measurement UUID. It then tries to attach an existing file to the measurement over the Raw Data Service

**Expected behavior**
The file "Test.png" should be correctly attached to the measurement.

**Additional context**
[test_createrawdata.zip](https://github.com/ZEISS-PiWeb/PiWeb-Api/files/4557919/test_createrawdata.zip)

**Comment by czdietrich** [comment]
Hello @czpercle, if I am not mistaken, the error comes from parsing the Content-MD5-header. I am not really familiar with python, but I think the header value has the wrong format in your script. The header is expected to use the `base64` format:
`Content-MD5: Q2h1Y2sgSW51ZwDIAXR5IQ==`

I guess the confusing point comes from the `RawDataInformation` object that uses `System.Guid` for representing the MD5-value. Under the hood the Guid-object is converted to a `byte array` and then formatted as `base64 string` before being set Content-MD5-header.

[Content-MD5](https://www.oreilly.com/library/view/http-the-definitive/1565925092/re17.html)

**Comment by czpercle** [comment]
That fixed it. I did not realize that the MD5 needed to be base64-encoded according to the RFC. This is now just an issue of documentation.
