### ISSUE TITLE
Add offered versions to ServerApiNotSupportedException

### ISSUE THREAD

**Issue by czkum** [ZEISS-PiWeb/PiWeb-Api#46]
**Situation**
The class `FeatureMatrix` currently throws `ServerApiNotSupportedException` in case the parameter `supportedVersions` doesn't contain any version supported by the client using the API. In such an error case the clients needs to catch the exception. Unfortunately, it is not possible to access the information about the versions offered by the server. It would be helpful to log those versions so the error would be more transparent.

**Requirement**
The exception `ServerApiNotSupportedException` provides the versions offered by the server service.

Think about renaming the _supported_ versions to _offered_ versions. The `ServerApiNotSupportedException` is thrown in case the server API is not supported by the client, i.e., if none of the versions _offered_ by the server are supported by the client. The word _supported_ would be misleading if used for the versions offered by the server.

**Example**
```
public bool IsFeatureXSupported()
{
  try
  {
    var featureMatrix = MyRestClient.GetFeatureMatrix();
    return featureMatrix.SupportsFeatureX;
  }
  catch( ServerApiNotSupportedException e )
  {
    _Logger.Log( $"Server API is not supported by this client. Offered versions by the server: {string.Join( ",", e.OfferedVersions )}" );
  }
}
```

**Comment by czthiele** [comment]
Done in PR #79. The exception now contains the versions supported by the server 👍
