### ISSUE TITLE
Inspection plan history

### ISSUE THREAD

**Issue by VolkerDannbeck** [ZEISS-PiWeb/PiWeb-Api#49]
**Affected Version(s)**
v5.0.1.

**Describe the bug**
When you change something in PiWebPlanner the inspection plan history is updated by PiWeb automatically.
When we change something via API calls the inspection plan history is updated too, but the "User" and the "Comment" is missing.

**To Reproduce**
Write a program to change characteristics or attributes via API calls.

**Expected behavior**
We would like to see the well maintained "User" and the "Comment" just as if we added this manually.

**Screenshots**
See attachment
![Inspection plan history](https://user-images.githubusercontent.com/71258750/95560199-37b4fb80-0a19-11eb-8078-b07c5c6f81eb.png)

**Comment by czthiele** [comment]
Hello @VolkerDannbeck 

the described behaviour is not exactly a bug but expected. The text shown in the versioning menu is given by PiWeb Planner via the versioning pop-up where you can enter the reason for your change. You would experience the same outcome if you leave this pop-up blank, and user/comment would be empty afterwards too.
The application using the API is responsible for filling this information using the Comment-property of parts/characteristics, simply set the property to the reason of your change before using DataServiceRestClient.UpdateParts/Characteristics.

A small hint: the format for the comment is "[Username]: Text" as seen in your screenshot. The user is parsed from this string, hence the brackets []. 

I just noticed that the documentation for versioning entries is very sparse, we will look into updating this soon.
