### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by czpercle** [ZEISS-PiWeb/PiWeb-Api#52]
**Affected Version(s)**
1.5

**Describe the bug**
The example return value for the parts/:partUuid GET endpoint is incorrect in the documentation.

**Expected behavior**
The endpoint returns a single object.

**Additional context**
The example for GET parts/:partUuid is copied from the GET parts endpoint. However, GET parts/:partUuid returns a single object, not an array as in the documentation.
This also happens with GET characteristics/:charUuid
GET measurement/:measUuid und GET values/:measUuid do return arrays, but this should be changed to only return a single object and the documentation changed accordingly.

**Comment by czthiele** [comment]
Thank you @czpercle for reporting this mistake.
Fixed with commit d3df91a.

We will discuss the issue regarding the measurement endpoint internally, since we need to take a look at the backwards compatibility.
