### ISSUE TITLE
Another documentation point

### ISSUE THREAD

**Issue by czpercle** [ZEISS-PiWeb/PiWeb-Api#55]
**Affected Version(s)**
1.5

**Describe the bug**
The documentation under endpoint GET configuration is incorrect.

**Expected documentation**
```
{
       "partAttributes":
       [
        {
            "key":1001,
            "description":"partNumber",
            "length":30,
            "type":"AlphaNumeric",
            "definitionType":"AttributeDefinition"
        },
...
```

**Current documentation**
```
{
       "partAttributes":
       [
        [
            "key":1001,
            "description":"partNumber",
            "length":30,
            "type":"AlphaNumeric",
            "definitionType":"AttributeDefinition"
        ],
...
```
(The arrays inside the xxxAttributes properties contain objects/dictionaries, not nested arrays.)

**Comment by czthiele** [comment]
Thank you @czpercle for reporting this mistake.
Fixed with commit https://github.com/ZEISS-PiWeb/PiWeb-Api/commit/d3df91abaacefb964cd2a47cf9f4a7b5dfafa93e
