### ISSUE TITLE
Weitere Request Beispiele bei der REST-API (PiWeb API)

### ISSUE THREAD

**Issue by HasemAljajeh** [ZEISS-PiWeb/PiWeb-Api#62]
Hallo,

Im Repository stehen nur 3 Examples (Fetching the attribute configuration, Fetching all parts und Fetching the 10 most recent measurements) zu Verfügung.

Ich möchte z.B. nach einer bestimmten uuid suchen und die Werte die am ganzen Tag gesammelt wurden sind anzeigen.
Anbei einen Screenshot.
![1](https://user-images.githubusercontent.com/75990275/102209215-bf632e80-3ed0-11eb-80af-4cffe76dfd28.png)

Dies funktioniert leider nicht.
 
Vielen Dank im Voraus.

Viele Grüße
Hasem Al Jajeh

**Comment by czthiele** [comment]
Hallo @HasemAljajeh,

die wesentlich umfangreichere Dokumentation finden Sie [hier](http://zeiss-piweb.github.io/PiWeb-Api/general), wie im Repository unter "Learn more" verlinkt. 
Unter dem Reiter [DataService](http://zeiss-piweb.github.io/PiWeb-Api/dataservice/v1.5/) finden Sie eine Dokumentation über alle Möglichkeiten die der DataService bietet. Der Abschnitt [Measurements and values](http://zeiss-piweb.github.io/PiWeb-Api/dataservice/v1.5/#ds-measurements-and-values) enthält eine Übersicht aller möglichen URL Parameter sowie deren Beschreibung beim Abrufen von Messwerten.

Für Ihr spezifisches Problem: Die URL im Screenshot ist soweit korrekt, wenn eine Messung mit dieser Uuid existiert, so sollte diese mit Werten zurückgegeben werden. Wichtig ist: jede Messung hat eine eigene Uuid, welche natürlich anders ist als die des Teils zu dem sie gehört. 
Beispielsweise können Sie mit

`Server/DataServiceRest/values?partPath=/Teil1/&searchCondition=4>[2020-12-15T00:00:00Z]`

alle Messungen zum Teil "Teil1" abrufen, die nach dem 15.12.2020 0 Uhr gemessen wurden (wobei 4 dem K-Schlüssel der Zeit der Messung entspricht). So tragen Sie einfach den aktuellen Tag ein und bekommen alle Messung vom bisherigen Tag. Sie können dort auch noch über Uuids auf Merkmale einschränken, für die Sie Messwerte sehen möchten. Am besten stöbern Sie mal durch die verlinkte Dokumentation.
Sollten weitere Fragen auftauchen, so können Sie diese gerne hier stellen.

Viele Grüße
Alexander Thiele
