### ISSUE TITLE
Value list is not resolved correctly in the format string from a filter tree

### ISSUE THREAD

**Issue by czmachowa** [ZEISS-PiWeb/PiWeb-Api#63]
**Affected Version(s)**
6.0.0

**Describe the bug**
If a format string is created from a filter tree, then the value list is not resolved correctly.

**To Reproduce**
1. Create a filter tree for "4 in ('foo', 'bar')".
2. Format the filter tree into a string.

**Current behavior**
The created format string is "4 in ('foo,bar')".

**Expected behavior**
The created format string is "4 in ('foo', 'bar')".

**Comment by daniel-schroeder-zeiss** [comment]
I cannot reproduce this behavior. In my tests all value lists are formatted as expected.
