### ISSUE TITLE
The NuGet information is incorrect

### ISSUE THREAD

**Issue by czdietrich** [ZEISS-PiWeb/PiWeb-Api#69]
**Affected Version(s)**
6.1.0

**Describe the bug**
At least he NuGet dependency block of the `Zeiss.PiWeb.Api.Rest` is incorrect. The actual NuGet references of the project are different from the dependencies stated in the .nuspec file of the resulting NuGet package. This can probably break dependency resolution for all consumers of this NuGet package, which will result in runtime errors.

**To Reproduce**
Simply compare the [PackageReferences](https://github.com/ZEISS-PiWeb/PiWeb-Api/blob/develop/src/Api.Rest/Api.Rest.csproj#L50) to the [NuSpec information](https://github.com/ZEISS-PiWeb/PiWeb-Api/blob/develop/build.cake#L228).

**Expected behavior**
Both information should match each other (keep in mind there could be transitive dependencies).

**Solution**
In a first step the version information should by updated manually.
On the long run, the cake script here should better be replaced by using `dotnet pack` for building packages, so there is no need to maintain such information in multiple places.

**Comment by czdietrich** [comment]
Another argument for using `dotnet pack` is to get the latest NuGet specifications.

The current approach doesn't seem to consider specific framework references, since this block is missing currently but would be created by `dotnet pack`:
```xml
...
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="System.Net.Http.WebRequest" targetFramework=".NETFramework4.8" />
    </frameworkAssemblies>
  </metadata>
</package>
```

**Comment by czdietrich** [comment]
I guess, we could delete the Cake scripts now, since they are no longer in use?

**Comment by czthiele** [comment]
Hello @czdietrich, correct, I have already created a PR for this. See #180
