### ISSUE TITLE
Performance-Problem bei Messungen zu einem Teil mit 2600 Merkmalen

### ISSUE THREAD

**Issue by NicasMaasackers** [ZEISS-PiWeb/PiWeb-Api#77]
**Used version**
PiWeb Server Version: 7.6.4

**Question**

Der Prüfplan eines "Teils" enthält ca. 2600 Merkmale. Jedes Merkmal spiegelt eine Messposition wieder. Da die Absolutwerte ausgewertet werden sollen, kommt ein Formplot für diesen Anwendungsfall nicht in Frage. Daher entstehen "so viele Merkmale".

Wir haben festgestellt, dass die Erstellung der 2600 Merkmale ca. 2 Stunden über die API gedauert hat. Anschließend hat das Übertragen von Messungen ca. 30 Minuten gedauert.

Können Sie mir / uns erklären, wie diese lange Bearbeitungszeit zustande kommt? Der Service selbst läuft stabil.

Freundliche Grüße

Niclas Maasackers

**Comment by czthiele** [comment]
Hallo @NicasMaasackers,

2 Stunden für 2600 Merkmale ist natürlich nicht normal. Legen Sie alle 2600 Merkmale mit einem API-Aufruf an, oder jedes Merkmal einzeln? Wie viele Attribute hängen an einem Merkmal? 
Da PiWeb intern selbst die API nutzt: haben Sie die Möglichkeit mittels dem PiWeb Planner mal beispielsweise über den Import 2600 Merkmale anzulegen? Bestenfalls vom gleichen PC von dem aus auch Ihr Programm die API anspricht. Dauert es mittels Planner ähnlich lang?

**Comment by NicasMaasackers** [comment]
Hallo @czthiele 

wir sprechen die API für jedes Merkmal einzeln an. Wobei uns schon aufgefallen ist, dass dabei mehrere Schleifen gedreht werden und somit hohe Durchlaufzeiten zustande kommen.
Hinter jedem Merkmal hängt nur der Merkmalsname.

Über den PiWeb Planner hat es ca. 5 - 10 Sekunden gedauert für 2600 Merkmale. Dies hat erstaunlich schnell funktioniert.

**Comment by czthiele** [comment]
Hallo @NicasMaasackers,

prinzipiell sollte dann das Anlegen über die API in einer ähnlichen Zeit gehen, der Planner nutzt ja genau diese. Die Empfehlung wäre an dieser Stelle ganz klar alle Merkmale in einem Aufruf anzulegen, anstatt jedes Merkmal einzeln. Darum erwartet die Methode in unserer C# SDK auch ein Array von Objekten, bzw für den Fall das Sie die HTTP API direkt ansprechen, einfach alle Merkmale in einem POST Request absenden. Wenn es dazu weitere Fragen gibt bin ich gern behilflich.
