### ISSUE TITLE
Further documentation issue

### ISSUE THREAD

**Issue by czpercle** [ZEISS-PiWeb/PiWeb-Api#78]
**Affected Version(s)**
v1.5

**Describe the bug**
The example for POST on the "parts" endpoint is incorrect.

**To Reproduce**
The example given is:
```
[
  {
    "uuid": "05040c4c-f0af-46b8-810e-30c0c00a379e",
    "path": "/metal part",
    "attributes": { "1001": "4466", "1003": "mp" }       
  }
]
```
To reproduce, send a POST request with that body to the "parts" endpoint of an empty database.

**Expected behavior**
HTTP status 201 and the part exists in the database.

**Additional context**
The example is rejected due to the path value. The example should read:
```
[
  {
    "uuid": "05040c4c-f0af-46b8-810e-30c0c00a379e",
    "path": "P:/metal part/",
    "attributes": { "1001": "4466", "1003": "mp" }       
  }
]
```

**Comment by czthiele** [comment]
Hi @czpercle,

thank you for reporting this issue. The documentation is now correct for POST and PUT examples.
