### ISSUE TITLE
Check the K keys

### ISSUE THREAD

**Issue by theklabrunner** [ZEISS-PiWeb/PiWeb-Api#8]
**Affected Version(s)**
2.0.7, 4.0.0

**Describe the bug**
In der Datei
https://github.com/ZEISS-PiWeb/PiWeb-Api/blob/develop/src/Common/Data/WellKnownKeys.cs
scheint der Schlüssel für
public const ushort GestampControlPoint = 860;
nicht zu stimmen.
Entweder er wird gar nicht verwendet oder er muss 960 heißen, so wie in der Konfigurationsvorlage für PiWeb:
"...\PiWeb\Shared Files\Qdb\databaseConfigurationGroups\de\KPI.qdb"

Vgl. mit [PIWEB-3731](https://bugtracker.zeiss-izm.de/browse/PIWEB-3731)

Außerdem in diesem Zusammenhang noch folgenden Fall bearbeiten:
[PIWEB-10781](https://bugtracker.zeiss-izm.de/browse/PIWEB-10781)

**Comment by czthiele** [comment]
Fixed with API 5.0.0-beta0001.
