### ISSUE TITLE
How to use "IN" operator in searchCondition

### ISSUE THREAD

**Issue by jdunkelmann** [ZEISS-PiWeb/PiWeb-Api#81]
Hi, I am loading measurements using the REST API which works fine as long as I use the "=" operator. I can't get the "IN" operator to work with catalog-based attributes though. I tried 
96 IN [1, 2]
96 IN ([1, 2])
96 IN [(1, 2)]
96 IN ([1], [2])
None of the above is working. Could you explain what the correct syntax is?
Thanks.

**Comment by nicoweh** [comment]
Hello jdunkelmann,
the first expression is correct but the operator is case sensitive.
Please use "Is" instead. In your example: "96 In [1, 2]"

**Comment by jdunkelmann** [comment]
Such as simple as that! Thanks, nicoweh!
