### ISSUE TITLE
Verbesserungsvorschlag: Option zum Schreiben von Attributen mit K+Nummer

### ISSUE THREAD

**Issue by ghost** [ZEISS-PiWeb/PiWeb-Api#84]
**Verwendete Version**
1.5/1.5 mit 7.8.4

**Vorschlag**
(Umzug des Vorschlags aus dem Bugtracker)
Als API-Benutzer möchte ich gern Attribute (insbesondere Messungs- und Messwertattribute) als "Kn" anstatt "n" angeben, um die Konvertierung zu und von XML zu ermöglichen.

**Hintergrund**
Der Kunde möchte einen gängigen XML-zu-JSON und JSON-zu-XML Konverter verwenden. Da eine bloße Zahl kein gültiges XML-Element darstellt, wird ein Anfangsbuchstabe benötigt.

**Comment by daniel-flemming** [comment]
Wir werden die API an dieser Stelle nicht ändern, da potentiell wenig Nutzen für relativ viel Komplexität entsteht. Aktuell kann "N" direkt in eine Zahl geparst werden und es braucht keinen Check, ob die Zeichenkette mit einem K beginnt. Das macht das Parsen sehr effizient. Die PiWeb API ist auf Geschwindigkeit und minimale Geschwätzigkeit optimiert, damit wir ein Maximum an Performance bieten können.

Für eine XML-Konvertierung muss potentiell (zumindest bei anderen Aufrufen) weiterer Code geändert werden, weil man sonst schnell an weitere Grenzen stößt. Ich glaube ein separater Konverterbaustein wäre hier die beste Lösung. Dann kann man die Konvertierung genau so bauen, wie es für den eigenen Anwendungsfall am besten passt.

Viele Grüße
Daniel.
