### ISSUE TITLE
Problem on creating the attribute K12005

### ISSUE THREAD

**Issue by MonicaMina** [ZEISS-PiWeb/PiWeb-Api#92]
Hello, I have a problem on creating the attribute K12005.
I would like to reference the catalog "Classification catalog yes/no with colors" in k12005, but I don't know how to do it. I tried to write "Classification catalog yes/no with colors" in the k-tag value, but it doesn't seem to work. 

Thanks in advance for your help

**Comment by czthiele** [comment]
Hello @MonicaMina,
at first please let me know if you are using our .NET SDK API Nuget, or if you are using the API over HTTP/REST.

**Comment by MonicaMina** [comment]
Hello, 
i'm using the API over REST.

**Comment by MonicaMina** [comment]
I reformulate the problem better:
i tried to write "Classification catalog yes/no with colors" in the k-tag value (K12005), and it works. I mean the measurement creation did not give me any errors, but in Piweb the k-tag K12005 is empty! Is it correct to use the plain text or I have to use the hexadecimal code or what? 

Thanks

**Comment by czthiele** [comment]
K12005 needs the Uuid of the desired catalog as the value. So instead of plain text  "Classification catalog yes/no with colors" you need to use the Uuid of the classification catalog. You can request the cataloges using .../DataServiceRest/Catalogs and search for the catalog "Classification catalog yes/no with colors" and its Uuid.

**Comment by MonicaMina** [comment]
Okay, thank you. And what function I have to use to search for a catalog by its name?

**Comment by czthiele** [comment]
You have to search through the list of all catalogs in your own script/application, since currently there is no way to request a specific catalog by its name. You can take a look at the examples in the [catalogs documentation](http://zeiss-piweb.github.io/PiWeb-Api/dataservice/v1.5/#ds-catalogs).
